auth:
  adminUser: admin
  adminPassword: admin123

service:
  type: ClusterIP
  ports:
    http: 8080  # явно указываем порт сервиса 8080

ingress:
  enabled: false

extraEnvVars:
  - name: KEYCLOAK_FRONTEND_URL
    value: "http://keycloak.local"
