apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-service
  labels:
    app: sink-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sink-service
  template:
    metadata:
      labels:
        app: sink-service
    spec:
      containers:
        - name: sink-service
          image: uncookie/sink-service:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sink-service
spec:
  selector:
    app: sink-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000