# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ingest.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ingest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cingest.proto\x12\nnica_proto\"2\n\rIngestRequest\x12\x10\n\x08\x64\x65tector\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x05\n\x03\x41\x63k2J\n\rIngestService\x12\x39\n\x0bIngestEvent\x12\x19.nica_proto.IngestRequest\x1a\x0f.nica_proto.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ingest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTREQUEST']._serialized_start=28
  _globals['_INGESTREQUEST']._serialized_end=78
  _globals['_ACK']._serialized_start=80
  _globals['_ACK']._serialized_end=85
  _globals['_INGESTSERVICE']._serialized_start=87
  _globals['_INGESTSERVICE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
